import type { Age, Civ, DraftStep, Leader, Player } from './types';

export const DATA: { ages: Age[]; leaders: Leader[]; civs: Civ[] } = {
  ages: ['Antiquity', 'Exploration', 'Modern'],
  leaders: [
    { id: 'l1', name: 'Ada Lovelace', attributes: ['Cultural', 'Scientific'], dlc: false },
    { id: 'l2', name: 'Amina', attributes: ['Economic', 'Militaristic'], dlc: false },
    { id: 'l3', name: 'Ashoka, World Conqueror', attributes: ['Diplomatic', 'Militaristic'], dlc: false },
    { id: 'l4', name: 'Ashoka, World Renouncer', attributes: ['Diplomatic', 'Expansionist'], dlc: false },
    { id: 'l5', name: 'Augustus', attributes: ['Cultural', 'Expansionist'], dlc: false },
    { id: 'l6', name: 'Benjamin Franklin', attributes: ['Diplomatic', 'Scientific'], dlc: false },
    { id: 'l7', name: 'Catherine', attributes: ['Cultural', 'Diplomatic'], dlc: false },
    { id: 'l8', name: 'Charlemagne', attributes: ['Militaristic', 'Scientific'], dlc: false },
    { id: 'l9', name: 'Confucius', attributes: ['Cultural', 'Scientific'], dlc: false },
    { id: 'l10', name: 'Edward Teach', attributes: ['Militaristic', 'Economic'], dlc: true },
    { id: 'l11', name: 'Friedrich, Baroque', attributes: ['Militaristic', 'Cultural'], dlc: false },
    { id: 'l12', name: 'Friedrich, Oblique', attributes: ['Militaristic', 'Scientific'], dlc: false },
    { id: 'l13', name: 'Genghis Khan', attributes: ['Militaristic', 'Expansionist'], dlc: false },
    { id: 'l14', name: 'Harriet Tubman', attributes: ['Diplomatic', 'Militaristic'], dlc: false },
    { id: 'l15', name: 'Hatshepsut', attributes: ['Cultural', 'Economic'], dlc: false },
    { id: 'l16', name: 'Himiko, High Shaman', attributes: ['Cultural', 'Diplomatic'], dlc: false },
    { id: 'l17', name: 'Himiko, Queen of Wa', attributes: ['Diplomatic', 'Scientific'], dlc: false },
    { id: 'l18', name: 'Ibn Battuta', attributes: ['Expansionist', 'Wildcard'], dlc: false },
    { id: 'l19', name: 'Isabella', attributes: ['Expansionist', 'Economic'], dlc: false },
    { id: 'l20', name: 'José Rizal', attributes: ['Cultural', 'Diplomatic'], dlc: false },
    { id: 'l21', name: 'Lafayette', attributes: ['Cultural', 'Diplomatic'], dlc: false },
    { id: 'l22', name: 'Lakshmibai', attributes: ['Militaristic', 'Diplomatic'], dlc: false },
    { id: 'l23', name: 'Machiavelli', attributes: ['Diplomatic', 'Economic'], dlc: false },
    { id: 'l24', name: 'Napoleon, Emperor', attributes: ['Economic', 'Diplomatic'], dlc: false },
    { id: 'l25', name: 'Napoleon, Revolutionary', attributes: ['Militaristic', 'Cultural'], dlc: false },
    { id: 'l26', name: 'Pachacuti', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'l27', name: 'Sayyida al Hurra', attributes: ['Militaristic', 'Diplomatic'], dlc: true },
    { id: 'l28', name: 'Simón Bolívar', attributes: ['Militaristic', 'Expansionist'], dlc: false },
    { id: 'l29', name: 'Tecumseh', attributes: ['Militaristic', 'Diplomatic'], dlc: false },
    { id: 'l30', name: 'Trung Trac', attributes: ['Militaristic', 'Scientific'], dlc: false },
    { id: 'l31', name: 'Xerxes, King of Kings', attributes: ['Economic', 'Militaristic'], dlc: false },
    { id: 'l32', name: 'Xerxes, the Achaemenid', attributes: ['Cultural', 'Economic'], dlc: false },
  ],
  civs: [
    { id: 'c1', age: 'Antiquity', name: 'Achaemenid Persian', attributes: ['Economic', 'Militaristic'], dlc: false },
    { id: 'c2', age: 'Antiquity', name: 'Aksumite', attributes: ['Cultural', 'Economic'], dlc: false },
    { id: 'c3', age: 'Antiquity', name: 'Assyrian', attributes: ['Militaristic', 'Scientific'], dlc: false },
    { id: 'c4', age: 'Antiquity', name: 'Carthaginian', attributes: ['Militaristic', 'Economic'], dlc: false },
    { id: 'c5', age: 'Antiquity', name: 'Egyptian', attributes: ['Cultural', 'Economic'], dlc: false },
    { id: 'c6', age: 'Antiquity', name: 'Greek', attributes: ['Cultural', 'Diplomatic'], dlc: false },
    { id: 'c7', age: 'Antiquity', name: 'Han', attributes: ['Diplomatic', 'Scientific'], dlc: false },
    { id: 'c8', age: 'Antiquity', name: 'Khmer', attributes: ['Expansionist', 'Scientific'], dlc: false },
    { id: 'c9', age: 'Antiquity', name: 'Mauryan', attributes: ['Militaristic', 'Scientific'], dlc: false },
    { id: 'c10', age: 'Antiquity', name: 'Maya', attributes: ['Diplomatic', 'Scientific'], dlc: false },
    { id: 'c11', age: 'Antiquity', name: 'Mississippian', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'c12', age: 'Antiquity', name: 'Roman', attributes: ['Cultural', 'Militaristic'], dlc: false },
    { id: 'c13', age: 'Antiquity', name: 'Silla', attributes: ['Economic', 'Diplomatic'], dlc: false },
    { id: 'c14', age: 'Antiquity', name: 'Tongan', attributes: ['Diplomatic', 'Expansionist'], dlc: false },
    { id: 'c15', age: 'Exploration', name: 'Abbasid', attributes: ['Cultural', 'Scientific'], dlc: false },
    { id: 'c16', age: 'Exploration', name: 'Bulgarian', attributes: ['Expansionist', 'Militaristic'], dlc: false },
    { id: 'c17', age: 'Exploration', name: 'Chola', attributes: ['Diplomatic', 'Economic'], dlc: false },
    { id: 'c18', age: 'Exploration', name: 'Hawaiian', attributes: ['Cultural', 'Expansionist'], dlc: false },
    { id: 'c19', age: 'Exploration', name: 'Icelandic', attributes: ['Cultural', 'Militaristic'], dlc: false },
    { id: 'c20', age: 'Exploration', name: 'Incan', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'c21', age: 'Exploration', name: 'Majapahit', attributes: ['Cultural', 'Economic'], dlc: false },
    { id: 'c22', age: 'Exploration', name: 'Ming', attributes: ['Economic', 'Scientific'], dlc: false },
    { id: 'c23', age: 'Exploration', name: 'Mongolian', attributes: ['Expansionist', 'Militaristic'], dlc: false },
    { id: 'c24', age: 'Exploration', name: 'Norman', attributes: ['Diplomatic', 'Militaristic'], dlc: false },
    { id: 'c25', age: 'Exploration', name: 'Pirate', attributes: ['Economic', 'Militaristic'], dlc: false },
    { id: 'c26', age: 'Exploration', name: 'Shawnee', attributes: ['Diplomatic', 'Economic'], dlc: false },
    { id: 'c27', age: 'Exploration', name: 'Songhai', attributes: ['Economic', 'Militaristic'], dlc: false },
    { id: 'c28', age: 'Exploration', name: 'Spanish', attributes: ['Economic', 'Militaristic'], dlc: false },
    { id: 'c29', age: 'Exploration', name: 'Vietnamese', attributes: ['Cultural', 'Expansionist'], dlc: false },
    { id: 'c30', age: 'Modern', name: 'American', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'c31', age: 'Modern', name: 'British', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'c32', age: 'Modern', name: 'Bugandan', attributes: ['Cultural', 'Expansionist'], dlc: false },
    { id: 'c33', age: 'Modern', name: 'French Imperial', attributes: ['Militaristic', 'Diplomatic'], dlc: false },
    { id: 'c34', age: 'Modern', name: 'Meiji Japanese', attributes: ['Militaristic', 'Scientific'], dlc: false },
    { id: 'c35', age: 'Modern', name: 'Mexican', attributes: ['Cultural', 'Diplomatic'], dlc: false },
    { id: 'c36', age: 'Modern', name: 'Mughal', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'c37', age: 'Modern', name: 'Nepalese', attributes: ['Diplomatic', 'Cultural'], dlc: false },
    { id: 'c38', age: 'Modern', name: 'Ottoman', attributes: ['Cultural', 'Militaristic'], dlc: false },
    { id: 'c39', age: 'Modern', name: 'Prussian', attributes: ['Militaristic', 'Diplomatic'], dlc: false },
    { id: 'c40', age: 'Modern', name: 'Qajar', attributes: ['Diplomatic', 'Expansionist'], dlc: false },
    { id: 'c41', age: 'Modern', name: 'Qing', attributes: ['Economic', 'Expansionist'], dlc: false },
    { id: 'c42', age: 'Modern', name: 'Russian', attributes: ['Cultural', 'Scientific'], dlc: false },
    { id: 'c43', age: 'Modern', name: 'Siamese', attributes: ['Cultural', 'Diplomatic'], dlc: false },
  ],
};

export const DLC_OPTIONS = ['DLC Pack A', 'DLC Pack B'];
export const styleNotes = [
  'Dark, cinematic background with deep charcoal panels and gold accents.',
  'High-contrast typography with serif-inspired headings for a premium feel.',
  'Soft metallic borders and gentle drop shadows for layered cards.',
  'Compact spacing with clear section hierarchy and segmented controls.',
  'Chips and badges use muted fills with gold highlights for emphasis.',
  'Buttons mix filled gold primary with outlined/ghost companions.',
  'Inputs are framed with subtle borders and warm focus rings.',
];
export const styleTokens = [
  '--color-bg: #0b0f12',
  '--color-card: #151b21',
  '--color-border: #2b3640',
  '--color-text: #f2e9d8',
  '--color-muted: #b6b0a2',
  '--color-primary: #c9a35b',
  '--color-primary-contrast: #140f07',
  '--color-accent: #7fa1b3',
  '--color-danger: #c65a4a',
  '--radius-sm: 6px',
  '--radius-md: 10px',
  '--radius-lg: 16px',
  '--shadow-sm: 0 6px 18px rgba(0, 0, 0, 0.35)',
  '--shadow-md: 0 12px 26px rgba(0, 0, 0, 0.4)',
  '--space-1/2/3/4/6/8: 4/8/12/16/24/32px',
  '--control-h: 42px',
  '--focus-ring: 0 0 0 3px rgba(201, 163, 91, 0.35)',
];
export const assumptions = [
  'La suppression d’un player demande une confirmation native (window.confirm).',
  'La validation du nom du player se fait à la perte de focus ou via Entrée.',
  'Les suggestions des tags restent limitées aux 6 premiers résultats filtrés.',
];

export const stepOptions: { id: DraftStep; label: string; enabled: boolean }[] = [
  { id: 'leaders', label: 'Leaders', enabled: true },
  { id: 'civs', label: 'Civilisations', enabled: true },
  { id: 'souvenirs', label: 'Souvenirs', enabled: false },
  { id: 'ages', label: 'Âges', enabled: false },
  { id: 'quests', label: 'Quêtes', enabled: false },
];

export const createSeed = () => Date.now().toString(36);
export const createPlayer = (index: number): Player => ({
  id: `p${index}-${Date.now()}`,
  name: `Player ${index}`,
  hasAllDLC: true,
  ownedDLC: [],
  forcedAttributes: [],
  draftedLeaders: [],
  draftedCivsByAge: {},
  selectedCivByAge: {},
});
